### ISSUE TITLE
error

### ISSUE THREAD

**Issue by MBogballe** [moggieuk/Happy-Hare#554] opened 2024-12-13 22:32 UTC
![Uden titel](https://github.com/user-attachments/assets/84cce762-51b3-43a8-a21f-742be5de79c3)

hi
i get these errors after updating to v3.0.1-26-g27c1c42f.
i can't find where the error is, has anyone else experienced this

it comes when the filament reaches the extruder

**Comment by Sparkss** [comment] 2024-12-14 03:59
This looks like a duplicate of Issue #553. Check your klipper log to be sure. But your screen looks just like mine and that was/is the cause.

https://github.com/moggieuk/Happy-Hare/issues/553

**Comment by moggieuk** [comment] 2024-12-14 04:51
FIxed.  Just force an update with `update-manager` (you may need to hit the refresh arrow so it can see the updated version.

Yes is duplicate of #553.

**Closed** 2024-12-14 04:58 UTC
Labels: duplicate, believe fixed / answered
